# Generated by Django 5.1.3 on 2024-12-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_customer_email_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"permissions": [("send_email", "you can send private email")]},
        ),
    ]
